"""Pydantic v2 schemas — the OpenAPI source of truth.

The skill derives ``tool_names`` (``<toolset>_<operationId>``) and the
dependency graph from ``/openapi.json`` (auto-generated by FastAPI from these
models + the router signatures). Keep operationIds stable — they ARE the
agent's tool names.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

# --- enums (Literal → OpenAPI enums, so the agent sees the valid values) ---
Priority = Literal["P1", "P2", "P3", "P4"]
IncidentStatus = Literal["new", "in_progress", "pending_user", "resolved", "closed", "escalated"]
IncidentCategory = Literal["hardware", "software", "network", "security", "performance"]
ChangeStatus = Literal[
    "draft", "submitted", "cab_approved", "scheduled",
    "implementing", "implemented", "closed", "rejected", "rolled_back",
]
ChangeType = Literal["normal", "emergency"]
ChangeRisk = Literal["low", "medium", "high"]
CiType = Literal["server", "service", "application", "database", "network", "storage"]
CiStatus = Literal["in_service", "maintenance", "retired"]
Role = Literal["requester", "agent", "manager"]


class User(BaseModel):
    id: str
    username: str
    role: Role
    on_call_for: list[str] = Field(default_factory=list)


class SLA(BaseModel):
    id: str
    priority: Priority
    response_mins: int
    resolution_mins: int
    breach_action: Literal["escalate"] = "escalate"


class CI(BaseModel):
    id: str
    name: str
    type: CiType
    owner: str
    status: CiStatus = "in_service"
    depends_on: list[str] = Field(default_factory=list)
    runs_on: list[str] = Field(default_factory=list)
    created_at: datetime


class Comment(BaseModel):
    id: str
    author: str
    body: str
    at: datetime


class HistoryEntry(BaseModel):
    action: str
    from_status: Optional[str] = None
    to_status: str
    at: datetime
    actor: str


class Incident(BaseModel):
    id: str
    title: str
    description: str
    priority: Priority
    status: IncidentStatus
    category: IncidentCategory
    assignee: Optional[str] = None
    requester: str
    affected_ci: Optional[str] = None
    linked_cis: list[str] = Field(default_factory=list)
    linked_changes: list[str] = Field(default_factory=list)
    comments: list[Comment] = Field(default_factory=list)
    resolution_note: Optional[str] = None
    sla_id: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    history: list[HistoryEntry] = Field(default_factory=list)
    allowed_actions: list[str] = Field(default_factory=list)


class Change(BaseModel):
    id: str
    title: str
    description: str
    type: ChangeType
    risk: ChangeRisk
    status: ChangeStatus
    requester: str
    implementer: Optional[str] = None
    affected_cis: list[str] = Field(default_factory=list)
    linked_incidents: list[str] = Field(default_factory=list)
    change_window: Optional[str] = None
    rollback_plan: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    history: list[HistoryEntry] = Field(default_factory=list)
    allowed_actions: list[str] = Field(default_factory=list)


class Event(BaseModel):
    """SSE wire format: ``event: itsm.event\\ndata: <Event json>``."""

    id: str
    ts: datetime
    actor: str
    action: str
    data: dict[str, Any] = Field(default_factory=dict)


# --- request bodies ---

class LoginRequest(BaseModel):
    username: str
    password: Optional[str] = None


class CreateIncidentRequest(BaseModel):
    title: str
    description: str = ""
    priority: Priority
    category: IncidentCategory
    affected_ci: Optional[str] = None


class CreateChangeRequest(BaseModel):
    title: str
    description: str = ""
    type: ChangeType = "normal"
    risk: ChangeRisk = "medium"
    affected_cis: list[str] = Field(default_factory=list)
    rollback_plan: Optional[str] = None


class AddCommentRequest(BaseModel):
    body: str


class LinkCiRequest(BaseModel):
    ci_id: str


class LinkChangeRequest(BaseModel):
    change_id: str


class LinkIncidentRequest(BaseModel):
    incident_id: str


class UpdatePriorityRequest(BaseModel):
    priority: Priority


class AssignRequest(BaseModel):
    assignee: Optional[str] = None  # omit → assign to the affected_ci's owner


class ScheduleChangeRequest(BaseModel):
    change_window: str


class ResolveIncidentRequest(BaseModel):
    resolution_note: Optional[str] = None


class UpdateCiStatusRequest(BaseModel):
    status: CiStatus
